database_name: PostgreSQL
sqlalchemy_uri: postgresql+psycopg2://postgres:XXXXXXXXXX@gateway.docker.internal:5432/analytics
cache_timeout: null
expose_in_sqllab: true
allow_run_async: false
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_file_upload: false
extra:
  allows_virtual_table_explore: true
uuid: b90d1451-c3b9-4f55-ab9a-f872d933a1f6
version: 1.0.0
